### ISSUE TITLE
Int64 Support

### ISSUE THREAD

**Issue by peteroreil** [maxdavidson/structly#103]
Is there a way of dealing with 64bit integers. 
Can you encode raw buffers with structly?

**Comment by maxdavidson** [comment]
You could either do it with a raw buffer once the alignment can be configured, or by using an ugly hack to modify a struct schema like this:

```js
const uint64be = Object.assign(struct({ lo: uint32be, hi: uint32be }), { byteAlignment: 8 })
const uint64le = Object.assign(struct({ hi: uint32le, lo: uint32le }), { byteAlignment: 8 })
```

In the future, I could maybe implement an arbitrary length integer using [BigInt](https://github.com/tc39/proposal-bigint).

**Comment by peteroreil** [comment]
Thanks for the reply and workaround
